"""Despliegue corazón streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FYTQjPDoOCdBA8X5BRo5Fxhq03S1MLSU

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

# -*- coding: utf-8 -*-
import numpy as np
import pandas as pd
import pickle
import streamlit as st

# ============================
# 1. Cargar el modelo entrenado
# ============================
filename = 'modelo-ensamble-clas.pkl'
with open(filename, "rb") as f:
    modelo, variables, labelencoder, min_max_scaler = pickle.load(f)

# ============================
# 2. Interfaz gráfica
# ============================
st.title('Predicción de Riesgo de Stroke/Ataque Cardíaco')

Edad = st.slider('Edad', min_value=18, max_value=100, value=50, step=1)
Nivel_Glucosa = st.slider('Nivel Promedio de Glucosa', min_value=50.0, max_value=300.0, value=100.0, step=0.1)
Hipertension = st.selectbox('¿Tiene Hipertensión?', ['No', 'Sí'])
Enfermedad_Cardiaca = st.selectbox('¿Tiene Enfermedad Cardíaca?', ['No', 'Sí'])
Casado = st.selectbox('¿Alguna vez se ha Casado?', ['No', 'Sí'])
Estado_Fumador = st.selectbox('Estado de Fumador', ['never smoked', 'formerly smoked', 'smokes', 'Unknown'])

# ============================
# 3. Preparar los datos
# ============================
datos = [[Edad, Nivel_Glucosa, Hipertension, Enfermedad_Cardiaca, Casado, Estado_Fumador]]
data = pd.DataFrame(datos, columns=['Edad', 'Nivel_Glucosa', 'Hipertension', 'Enfermedad_Cardiaca', 'Casado', 'Estado_Fumador'])

# Mapear a las variables esperadas
data_preparada = data.copy()
data_preparada['age'] = data_preparada['Edad']
data_preparada['avg_glucose_level'] = data_preparada['Nivel_Glucosa']
data_preparada['hypertension'] = data_preparada['Hipertension'].map({'Sí': 'Yes', 'No': 'No'})
data_preparada['heart_disease'] = data_preparada['Enfermedad_Cardiaca'].map({'Sí': 'Yes', 'No': 'No'})
data_preparada['ever_married'] = data_preparada['Casado'].map({'Sí': 'Yes', 'No': 'No'})
data_preparada['smoking_status'] = data_preparada['Estado_Fumador']

# Eliminar columnas originales
data_preparada = data_preparada.drop(columns=['Edad','Nivel_Glucosa','Hipertension','Enfermedad_Cardiaca','Casado','Estado_Fumador'])

# One-hot encoding
data_preparada = pd.get_dummies(
    data_preparada,
    columns=['smoking_status','hypertension','heart_disease','ever_married'],
    drop_first=False,
    dtype=int
)

# Reindexar para que coincida con las variables del modelo
data_preparada = data_preparada.reindex(columns=variables, fill_value=0)

# Normalizar variables numéricas
data_preparada[['age','avg_glucose_level']] = min_max_scaler.transform(data_preparada[['age','avg_glucose_level']])

# ============================
# 4. Predicción
# ============================
Y_pred_encoded = modelo.predict(data_preparada)
Y_pred_labels = labelencoder.inverse_transform(Y_pred_encoded)

data['Prediccion'] = Y_pred_labels

# Mostrar resultados
st.dataframe(data)
st.success(f"Predicción: {Y_pred_labels[0]}")
st.warning("El modelo tiene un F1 Score aproximado del 88%")

