# -*- coding: utf-8 -*-
"""Despliegue corazón streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FYTQjPDoOCdBA8X5BRo5Fxhq03S1MLSU

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

# cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-ensamble-clas.pkl'
modelo, variables, labelencoder, min_max_scaler = pickle.load(open(filename, 'rb'))

#Cargamos los datos futuros
#data = pd.read_excel("predecir mortalidad_ataques_cardiacos.xlsx")
#data.head()

#!pip install streamlit

# Aquí va la interfaz gráfica
#Interfaz gráfica

#Se crea interfaz gráfica con streamlit para captura de los datos



import streamlit as st


st.title('Predicción de Riesgo de Stroke/Ataque Cardíaco')



Edad = st.slider('Edad', min_value=18, max_value=100, value=50, step=1)

Nivel_Glucosa = st.slider('Nivel Promedio de Glucosa', min_value=50.0, max_value=300.0, value=100.0, step=0.1)

Hipertension = st.selectbox('¿Tiene Hipertensión?', ['No', 'Sí'])

Enfermedad_Cardiaca = st.selectbox('¿Tiene Enfermedad Cardíaca?', ['No', 'Sí'])

Casado = st.selectbox('¿Alguna vez se ha Casado?', ['No', 'Sí'])

Estado_Fumador = st.selectbox('Estado de Fumador', ['never smoked', 'formerly smoked', 'smokes', 'Unknown'])




#Dataframe
datos = [[Edad, Nivel_Glucosa, Hipertension, Enfermedad_Cardiaca, Casado, Estado_Fumador]]

data = pd.DataFrame(datos, columns=['Edad', 'Nivel_Glucosa', 'Hipertension', 'Enfermedad_Cardiaca', 'Casado', 'Estado_Fumador']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación
data_preparada=data.copy()

# Rename and map columns to match model's expected features
data_preparada['age'] = data_preparada['Edad']
data_preparada['avg_glucose_level'] = data_preparada['Nivel_Glucosa']
data_preparada['hypertension'] = data_preparada['Hipertension'].map({'Sí': 'Yes', 'No': 'No'})
data_preparada['heart_disease'] = data_preparada['Enfermedad_Cardiaca'].map({'Sí': 'Yes', 'No': 'No'})
data_preparada['ever_married'] = data_preparada['Casado'].map({'Sí': 'Yes', 'No': 'No'})
data_preparada['smoking_status'] = data_preparada['Estado_Fumador']

# Drop original Streamlit input columns
data_preparada = data_preparada.drop(columns=['Edad', 'Nivel_Glucosa', 'Hipertension', 'Enfermedad_Cardiaca', 'Casado', 'Estado_Fumador'])

# One-hot encode categorical variables
# In despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['smoking_status', 'hypertension', 'heart_disease', 'ever_married'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza las variables numéricas para predecir con Knn, Red, SVM
#En los despliegues no se llama fit
data_preparada[['age', 'avg_glucose_level']]= min_max_scaler.transform(data_preparada[['age', 'avg_glucose_level']])
data_preparada.head()

"""# **Predicciones**"""

# Realizamos la predicción con el modelo de clasificación
# Primero, obtenemos las etiquetas numéricas predichas
Y_pred_encoded = modelo.predict(data_preparada)

# Luego, usamos el labelencoder para transformar las etiquetas numéricas a sus nombres originales
Y_pred_labels = labelencoder.inverse_transform(Y_pred_encoded)
print(Y_pred_labels)

data['Prediccion']=Y_pred_labels
data.head()

#predicciones finales
st.dataframe(data)

# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 6.55%")
